### ISSUE TITLE
How to join?

### ISSUE THREAD

**Issue by galm1diezero** [beeth9/beeth9#2]
I tried to find entrance but failed, is there any `guideline` to join?

**Comment by galm2pixy1991** [comment]
how?

**Comment by fdingiit** [comment]
> I tried to find entrance but failed, is there any `guideline` to join?

pay x1x to win 
@galm1diezero @galm2pixy1991

**Comment by galm1diezero** [comment]
From GitHub official [help website](https://help.github.com/en/articles/inviting-users-to-join-your-organization) , `ONLY organization owners` can **invite** users to join an organization. For more information, see [Permission levels for an organization](https://help.github.com/en/articles/permission-levels-for-an-organization).
